// Mock test data for development
export const mockUsers = [
  {
    id: '1',
    name: 'Ahmed Al-Balushi',
    email: 'ahmed@example.com',
    wallet_balance: 25.50,
    eco_credits: 145,
    total_rides: 28,
    rating: 4.8,
  },
  {
    id: '2',
    name: 'Fatima Al-Harthi',
    email: 'fatima@example.com',
    wallet_balance: 18.00,
    eco_credits: 210,
    total_rides: 42,
    rating: 4.9,
  },
  {
    id: '3',
    name: 'Mohammed Al-Lawati',
    email: 'mohammed@example.com',
    wallet_balance: 32.75,
    eco_credits: 189,
    total_rides: 35,
    rating: 4.7,
  },
];

export const mockRides = [
  {
    id: 'ride-1',
    from_location: 'Seeb',
    to_location: 'Indian School Muscat',
    from_lat: 23.5880,
    from_lng: 58.3829,
    to_lat: 23.5990,
    to_lng: 58.4090,
    date: new Date().toISOString().split('T')[0],
    time: '07:00 AM',
    seats_available: 3,
    seats_total: 4,
    price_per_seat: 2,
    distance_km: 12.5,
    driver_id: '1',
    driver: {
      name: 'Ahmed Al-Balushi',
      rating: 4.8,
    },
    status: 'active',
    passengers: [],
  },
  {
    id: 'ride-2',
    from_location: 'Al Khuwair',
    to_location: 'BRCA School',
    from_lat: 23.5975,
    from_lng: 58.4387,
    to_lat: 23.6125,
    to_lng: 58.4455,
    date: new Date().toISOString().split('T')[0],
    time: '07:30 AM',
    seats_available: 2,
    seats_total: 4,
    price_per_seat: 1.5,
    distance_km: 8.3,
    driver_id: '2',
    driver: {
      name: 'Fatima Al-Harthi',
      rating: 4.9,
    },
    status: 'active',
    passengers: [],
  },
  {
    id: 'ride-3',
    from_location: 'Ruwi',
    to_location: 'Pakistan School',
    from_lat: 23.5880,
    from_lng: 58.5456,
    to_lat: 23.5990,
    to_lng: 58.5600,
    date: new Date().toISOString().split('T')[0],
    time: '06:45 AM',
    seats_available: 4,
    seats_total: 5,
    price_per_seat: 2.5,
    distance_km: 15.2,
    driver_id: '3',
    driver: {
      name: 'Mohammed Al-Lawati',
      rating: 4.7,
    },
    status: 'active',
    passengers: [],
  },
];

export const mockLeaderboard = [
  { name: 'Fatima Al-Harthi', eco_credits: 210, total_rides: 42, rating: 4.9 },
  { name: 'Mohammed Al-Lawati', eco_credits: 189, total_rides: 35, rating: 4.7 },
  { name: 'Ahmed Al-Balushi', eco_credits: 145, total_rides: 28, rating: 4.8 },
  { name: 'Layla Al-Hinai', eco_credits: 132, total_rides: 25, rating: 4.6 },
  { name: 'Khalid Al-Rawas', eco_credits: 118, total_rides: 22, rating: 4.5 },
];
